language: php

php:
  - 5.5
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=strict

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  - composer selfupdate
  - ./bin/console doctrine:database:create
  - ./bin/console doctrine:schema:create
  - ./bin/console doctrine:fixtures:load --no-interaction

install:
  - composer update --prefer-dist --no-interaction

script:
  - phpunit
